### ISSUE TITLE
The change of answer start position

### ISSUE THREAD

**Issue by 21644h** [Yulong-W/mrcdr#1]
Hi, I have read your paper and code. As we know, the model calculates the loss or F1 score using the index of the answer which is given in the dataset (namely the "answer_start" in the json file). I wonder that if you shuffle the context, how do you calculate the new "answer_start"? It seems that neither the paper nor the code mentioned this.
Thank you.

**Comment by Yulong-W** [comment]
Hi, thanks for your interest. For evaluation the “answer_start” is not used, it is just based on surface form. Please check the corresponding transformers data https://github.com/huggingface/transformers/blob/2ce0fb84cc500a26b0c45bec1f8a42e33d13e05d/src/transformers/data/processors/squad.py#L551 :)

**Comment by 21644h** [comment]
Oh, I see. Thanks for your reply.
